config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  use_doorkeeper
  devise_for :users
  
  draw :api

  root 'documentation#index', as: 'documentation'

  get '/documentation', to: 'documentation#index'
  get '/documentation/authentication', to: 'documentation#authentication'
  get '/documentation/users', to: 'documentation#users'
  get '/documentation/cars', to: 'documentation#cars'
  get '/documentation/reservations', to: 'documentation#reservations'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :photo, presence: true
  validates :car_model, presence: true
  validates :price_per_day, numericality: { greater_than_or_equal_to: 0 }
  validates :user, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :date, presence: true
  validates :city, presence: true
  validates :duration, numericality: { greater_than_or_equal_to: 1 }
  validates :user, presence: true
  validates :car, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, format: URI::MailTo::EMAIL_REGEXP
  # enum role: %i[user admin]
  def self.authenticate(email, password)
    user = User.find_for_authentication(email:)
    user&.valid_password?(password) ? user : nil
  end
  validates :username, presence: true

  validates :username, length: { minimum: 3, maximum: 70 }

  has_many :reservations
end

app/controllers/api/v1/cars_controller.rb
module Api
  module V1
    class CarsController < ApiController
      before_action :doorkeeper_authorize!
      before_action :current_user
      respond_to :json

      def index
        @cars = Car.all
        render json: @cars
      end

      def create
        car = Car.new(car_params)
        if car.save
          render json: car, status: :created
        else
          render json: { errors: car.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def show
        @car = Car.find(params[:id])
        render json: @car
      end

      def destroy
        @car = Car.find(params[:id])
        @car.destroy
        render json: { message: 'Car deleted' }, status: :ok
      end

      private

      def car_params
        params.require(:car).permit(:name, :description, :photo, :price_per_day, :car_model, :user_id)
      end
    end
  end
end

app/controllers/api/v1/client_controller.rb
module Api
  module V1
    class ClientController < ApiController
      skip_before_action :doorkeeper_authorize!, only: %i[react]

      # GET /client.json
      def react
        @react_client = Doorkeeper::Application.find_by(name: 'React')
        if @react_client.nil?
          render json: { error: 'no React Client Present' }, status: :unprocessable_entity
        else
          render json: {
            id: @react_client.id,
            name: @react_client.name,
            uid: @react_client.uid,
            secret: @react_client.secret,
            redirect_uri: @react_client.redirect_uri,
            scopes: @react_client.scopes,
            confidential: @react_client.confidential,
            created_at: @react_client.created_at.iso8601
          }, status: :ok
        end
      end
    end
  end
end

app/controllers/api/v1/reservations_controller.rb
module Api
  module V1
    class ReservationsController < ApiController
      before_action :doorkeeper_authorize!
      before_action :current_user
      respond_to :json

      def index
        if @current_user.nil?
          render json: { error: 'Not Authorized' }, status: :unauthorized
        else
          @reservations = @current_user.reservations
          render json: @reservations
        end
      end

      def show
        @reservations = Reservation.where(user_id: params[:id])
        render json: { message: 'Showing Reservations', reservations: @reservations }, status: :ok
      end

      def create
        @reservation = Reservation.new(reservation_params)
        @reservation.user = @current_user
        if @reservation.save
          render json: { reservation: @reservation }, status: :created
        else
          render json: { errors: @reservation.errors }, status: :unprocessable_entity
        end
      end

      private

      def reservation_params
        params.require(:reservation).permit(:date, :item, :city, :duration, :car_id, :user_id)
      end
    end
  end
end

app/controllers/api/v1/users/registrations_controller.rb
module Api
  module V1
    module Users
      class RegistrationsController < ApiController
        skip_before_action :doorkeeper_authorize!, only: %i[create]

        include DoorkeeperRegisterable

        def create
          client_app = Doorkeeper::Application.find_by(uid: user_params[:client_id])
          unless client_app
            return render json: { error: I18n.t('doorkeeper.errors.messages.invalid_client') },
                          status: :unauthorized
          end

          allowed_params = user_params.except(:client_id)
          user = User.new(allowed_params)

          if user.save
            render json: render_user(user, client_app), status: :ok
          else
            render json: { errors: user.errors }, status: :unprocessable_entity
          end
        end

        private

        def user_params
          params.permit(:username, :email, :password, :client_id)
        end
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApiController
      before_action :doorkeeper_authorize!
      before_action :current_user
      respond_to :json

      # GET /me.json
      def me
        if @current_user.nil?
          render json: { error: 'Not Authorized' }, status: :unauthorized
        else
          render json: {
            username: @current_user.username,
            id: @current_user.id,
            email: @current_user.email,
            created_at: @current_user.created_at.iso8601
          }, status: :ok
        end
      end
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
  # equivalent of authenticate_user! on devise, but this one will check the oauth token
  # before_action :authenticate_user!
  before_action :doorkeeper_authorize!

  # Skip checking CSRF token authenticity for API requests.
  # skip_before_action :verify_authenticity_token

  # Set response type
  respond_to :json

  # helper method to access the current user from the token
  def current_user
    return unless doorkeeper_token

    @current_user ||= User.find_by(id: doorkeeper_token[:resource_owner_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/dookeeper_registerable.rb
module DoorkeeperRegisterable
  extend ActiveSupport::Concern

  def generate_refresh_token
    loop do
      # generate a random token string and return it
      # unless there is already another token with the same string
      token = SecureRandom.hex(32)
      break token unless Doorkeeper::AccessToken.exists?(refresh_token: token)
    end
  end

  def render_user(user, client_app, token_type = 'Bearer')
    access_token = Doorkeeper::AccessToken.create(resource_owner_id: user.id,
                                                  application_id: client_app.id,
                                                  refresh_token: generate_refresh_token,
                                                  expires_in: Doorkeeper.configuration.access_token_expires_in.to_i,
                                                  scopes: '')

    {
      id: user.id,
      email: user.email,
      # role: user.role,
      username: user.username,
      access_token: access_token.token,
      token_type:,
      expires_in: access_token.expires_in,
      refresh_token: access_token.refresh_token,
      created_at: access_token.created_at.to_time.to_i
    }
  end
end

app/controllers/documentation_controller.rb
class DocumentationController < ApplicationController
  def index
    render 'index'
  end

  def authentication
    render 'authentication'
  end

  def users
    render 'users'
  end

  def classes
    render 'classes'
  end

  def reservations
    render 'reservations'
  end
end

app/views/documentation/_navigation.html.erb
<div class="navbar navbar-expand-lg mb-5 navbar-dark bg-dark fixed-top">
  <%= image_tag("logo.png", class:"rounded-circle", style: "height: 80px; width: 80px;", alt: "Logo")%>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item <%= 'active' if current_page?(documentation_path) %>">
        <%= link_to "Home", documentation_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(documentation_authentication_path) %>">
        <%= link_to "Authentication", documentation_authentication_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(documentation_users_path) %>">
        <%= link_to "Users", documentation_users_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(documentation_cars_path) %>">
        <%= link_to "Cars", documentation_cars_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(documentation_reservations_path) %>">
        <%= link_to "Reservations", documentation_reservations_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>

app/views/documentation/authentication.html.erb
<div class="home pt-8items-center ml-60 p-4 h-screen">
  <%= render partial: "documentation/navigation" %>
    <div class="d-flex" style= "margin-top:100px">
    <section class="max-w-[800px] self-start flex flex-col">
      <h1 class="text-3xl font-bold mb-4">Authentication Endpoints</h1>
      <h2 class="text-xl font-bold mb-2 ml-2">POST oauth/token</h2>
      <p class="px-4 py-2">This endpoint allows users to log in to the application by providing their name, email,  password client_id client_secret If the credentials are correct, the server will respond with a token that can be used for authenticated requests.</p>
      <div class="px-4 pt-2">
        <h3 class="text-lg font-bold mb-2 ml-2">Request Parameters</h3>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Data Type</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>email</td>
              <td>string</td>
              <td>The email address of the user</td>
            </tr>
            <tr>
              <td>password</td>
              <td>string</td>
              <td>The password of the user</td>
            </tr>
            <tr>
              <td>grant_type</td>
              <td>string</td>
              <td>Type of Login Call Autherization</td>
            </tr>
            <tr>
              <td>client_id</td>
              <td>string</td>
              <td>Client ID generated by react Door Keeper</td>
            </tr>
            <tr>
              <td>client_secret</td>
              <td>string</td>
              <td>Client Secret generated by react Door Keeper</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="px-4 pt-4">
        <h3 class="text-lg font-bold mb-2 ml-2">Response</h3>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Status Code</th>
              <th>Response Body</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>200</td>
              <td>
              <code>
                    {
                        "access_token": "Vz_wqkl2QC4mSAv_BsokgxuJqnUlFGDcWprKvl35XdY",
                        "token_type": "Bearer",
                        "expires_in": 7200,
                        "refresh_token": "7pD7EGGv_LtfaFFk9ZEwWLP_v0Rux-Ypj41iqfd2d7Q",
                        "created_at": 1681383304
                    }
                </code>
                </td>
              <td>The token and the name that can be used for subsequent authenticated requests</td>
            </tr>
            <tr>
              <td>400</td>
              <td>
              <code>
                        {
                            "error": "invalid_grant",
                            "error_description": "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
                        }             
              </code>
              </td>
              <td>The email or password is incorrect and the login attempt is rejected</td>
            </tr>
          </tbody>
        </table>
  <div class="px-4 pt-6">
    <h3 class="text-2xl font-bold mb-2">Example Request</h3>
    <div class="card bg-dark border-0 rounded-xl mx-4 my-6">
      <h3 class="card-header bg-white text-dark font-bold">Ruby</h3>
      <div class="card-body bg-white rounded-xl">
        <pre class="m-0 bg-light">
          <code class="text-sm  max-h-80 m-0">
                  require 'net/http'
                  require 'json'

                  uri = URI('http://localhost:3000/api/v1/oauth/token')

                  params = {
                    'grant_type' => 'password',
                    'email' => 'admin@example.com',
                    'password' => 'password',
                    'client_id' => 'hlYgGHg3_MTSCiRswfvL4mEQqDUVHMrxmRKNieBOios',
                    'client_secret' => 'QRo8UcdaNy_D1cq3tfnLlHNcm4aR4mlQAqfoho2jxmI'
                  }

                  response = Net::HTTP.post_form(uri, params)
                  access_token = JSON.parse(response.body)['access_token']



          </code>
        </pre>
      </div>
    </div>
  </div>
  </div>
    </section>
  </div>
</div>

app/views/documentation/index.html.erb
<div class="home pt-8 align-items-center p-4 vh-100">
  <%= render partial: "documentation/navigation" %>
  <div class="d-flex" style= "margin-top:100px">
  <section class="max-w-600 self-start d-flex flex-column">
    <h1 class="text-3xl font-weight-bold mb-4">Welcome to the Coders Hub API Documentation</h1>
    <h2 class="text-xl font-weight-bold mb-2 ml-2">What is the Mentor Plus API?</h2>
    <p class="px-4 py-2">
      Our API is organized with
      <a class="text-blue-500 hover:text-blue-700 underline"
        href="https://en.wikipedia.org/wiki/Representational_state_transfer"
        target="_blank"
      >
        REST.
      </a>
      Our API has predictable resource-oriented URLs, accepts form-encoded
      request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and
      verbs.
    </p>
    <p class="px-4 py-2">
      It's a simple API that is linked to the
      <a class="text-blue-500 hover:text-blue-700 underline"
        href = "https://codershub-8u8o.onrender.com/"
        target="_blank"
      >
        Book-An-Appointment_front
      </a>. It holds all the data for the frontend to display, as well as the information of
      the users <em>(Usernames, Emails & Passwords)</em>.
    </p>
  </section>
  <section class="self-start p-2 w-37 h-100  d-flex flex-column justify-content-start align-items-start">
    <div class="base-url mb-8 bg-dark text-white rounded-lg w-100">
      <h3 class="text-xl font-weight-bold text-center p-2">Base URL</h3>
      <p class="px-4 py-2 bg-white text-center">
        <span class="text-primary font-monospace">https://coders-hub.onrender.com/api/v1/</span>
      </p>
    </div>
  </section>
  </div>
</div>

app/views/documentation/reservations.html.erb
<div class="home pt-8 items-center ml-60 p-4 h-screen">
  <%= render partial: "documentation/navigation" %>
    <div class="d-flex" style= "margin-top:100px">

  <section class="max-w-[800px] self-start flex flex-col">
    <h1 class="text-3xl font-bold mb-4">Reservations Endpoints</h1>
<div class="container mt-5">
  <h2 class="text-xl font-bold mb-2">GET /user/reservations</h2>
  <p class="px-4 py-2">Returns a list of all Reservations.</p>

  <div class="px-4 pt-6">
    <h3 class="text-2xl font-bold mb-2">Response</h3>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th class="px-4 py-2">Status Code</th>
            <th class="px-4 py-2">Response Body</th>
            <th class="px-4 py-2">Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="border px-4 py-2"><code>200</code></td>
            <td class="border px-4 py-2 font-weight-bold text-sm">
              <code>
   {
        "id": 3,
        "car_id": 2,
        "user_id": 1,
        "duration": 5,
        "item": "Toyota Cramy",
        "date": "2023-04-22",
        "city": "NewYork",
        "created_at": "2023-04-11T15:55:45.885Z",
        "updated_at": "2023-04-11T15:55:45.885Z"
    },
    <br>
    <br>
    {
        "id": 4,
        "car_id": 2,
        "user_id": 1,
        "duration": 5,
        "item": "Toyota Cramy",
        "date": "2023-05-03",
        "city": "eeeee",
        "created_at": "2023-04-11T15:56:21.165Z",
        "updated_at": "2023-04-11T15:56:21.165Z"
    },
    <br>
    <br>
    {
        "id": 5,
        "car_id": 2,
        "user_id": 1,
        "duration": 5,
        "item": "Toyota Cramy",
        "date": "2023-04-13",
        "city": "sjsjsjks",
        "created_at": "2023-04-11T17:23:59.421Z",
        "updated_at": "2023-04-11T17:23:59.421Z"
    },
    <br>
    <br>
    {
        "id": 6,
        "car_id": 2,
        "user_id": 1,
        "duration": 5,
        "item": "Toyota Cramy",
        "date": "2023-04-20",
        "city": "hell",
        "created_at": "2023-04-11T18:55:06.151Z",
        "updated_at": "2023-04-11T18:55:06.151Z"
    }
              </code>
            </td>
            <td class="border px-4 py-2">A list of all reservation for the logged in users  in the system</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="px-4 pt-6">
    <h3 class="text-2xl font-bold mb-2">Example Request</h3>
    <div class="card bg-dark border-0 rounded-xl mx-4 my-6">
      <h3 class="card-header bg-white text-dark font-bold">Ruby</h3>
      <div class="card-body bg-white rounded-xl">
        <pre class="m-0 bg-light">
          <code class="text-sm  max-h-80 m-0">
                  require 'net/http'
                  require 'json'

                  url = URI('http://127.0.0.1:3000/api/v1/users')
                   headers = {
                  require 'net/http'

                  # Set the URL and headers
                  url = URI('http://127.0.0.1:3000/api/v1/user/reservations')
                  headers = {
                    'Authorization' => 'Bearer < Token >'
                  }

                  # Create a new HTTP object
                  http = Net::HTTP.new(url.host, url.port)

                  # Enable HTTPS if necessary
                  http.use_ssl = (url.scheme == 'https')

                  # Create a new GET request with the headers
                  request = Net::HTTP::Get.new(url, headers)

                  # Send the request and get the response
                  response = http.request(request)

                  case response.code
                  when '200'
                    # Handle successful response
                    puts response.body
                  when '401'
                    # Handle unauthorized error
                    puts 'Error: Unauthorized'
                  else
                    # Handle other errors
                    puts "Error: #{response.code} #{response.message}"
                  end          </code>
        </pre>
      </div>
    </div>
  </div>
</div>

 <div class="container mx-auto px-4 pt-6">
    <h2 class="text-xl font-bold mb-2">POST /user/reserve</h2>
    <p class="px-4 py-2">Creates a new reservation in the system.</p>
    <div class="px-4 pt-6">
        <h3 class="text-lg font-bold mb-2">Parameters</h3>
    <div class="table-responsive">
      <table class="table table-striped">
            <thead>
                <tr>
                    <th class="px-4 py-2">Name</th>
                    <th class="px-4 py-2">Data Type</th>
                    <th class="px-4 py-2">Description</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="border px-4 py-2">date</td>
                    <td class="border px-4 py-2">Date</td>
                    <td class="border px-4 py-2">The date of the reservation</td>
                </tr>
                <tr>
                    <td class="border px-4 py-2">city</td>
                    <td class="border px-4 py-2">String</td>
                    <td class="border px-4 py-2">The city where the reservation takes place</td>
                </tr>
                <tr>
                    <td class="border px-4 py-2">car_id</td>
                    <td class="border px-4 py-2">Integer</td>
                    <td class="border px-4 py-2">car_id of the cars user wants to reserve</td>
                </tr>
                    
            </tbody>
        </table>
    </div>
    <div class="px-4 pt-6">
        <h3 class="text-lg font-bold mb-2">Response</h3>
        <table class="table-auto w-full">
            <thead>
                <tr>
                    <th class="px-4 py-2">Status Code</th>
                    <th class="px-4 py-2">Response Body</th>
                    <th class="px-4 py-2">Description</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="border px-4 py-2"><code>201</code></td>
                    <td class="border px-4 py-2 font-bold text-sm">
                        <code>
                          {
                              "id": 17,
                              "car_id": 2,
                              "user_id": 1,
                              "duration": 5,
                              "item": "Toyota Cramy",
                              "date": "2023-11-11",
                              "city": "Berlin",
                              "created_at": "2023-04-13T06:26:13.673Z",
                              "updated_at": "2023-04-13T06:26:13.673Z"
                            }
                        </code>
                    </td>
                    <td class="border px-4 py-2">The newly created reservation</td>
                </tr>
                                <tr>
                    <td class="border px-4 py-2"><code>422</code></td>
                    <td class="border px-4 py-2 font-bold text-sm">
                        <code>
                            {
                                    "date": [
                                        "can't be blank"
                                    ]
                            }
                        </code>
                    </td>
                    <td class="border px-4 py-2">Unsuccessful due to validation errors</td>
                </tr>
            </tbody>
        </table>
    </div>
  <div class="px-4 pt-6">
    <h3 class="text-2xl font-bold mb-2">Example Request</h3>
    <div class="card bg-dark border-0 rounded-xl mx-4 my-6">
      <h3 class="card-header bg-white text-dark font-bold">Ruby</h3>
      <div class="card-body bg-white rounded-xl">
        <pre class="m-0 bg-light">
          <code class="text-sm  max-h-80 m-0">
               require 'net/http'
                require 'json'

                uri = URI('http://127.0.0.1:3000/api/v1/user/reserve')
                user_authenticated = true # replace with your authentication logic
                car_id = 123 # replace with the car_id received in the request
                valid_parameters = true # replace with your parameter validation logic

                if !user_authenticated
                  puts "User is not authenticated, sending 401 Unauthorized error"
                  response = Net::HTTPUnauthorized.new(1.0, 'Unauthorized')
                elsif valid_parameters
                  puts "User is authenticated and parameters are valid, reserving car for user"
                  data = { "car_id": car_id, "class": "class_name" } # replace with the required parameters
                  response = Net::HTTP.post(uri, data.to_json, 'Content-Type' => 'application/json')
                  if response.code == '201'
                    puts "car reserved for user with status code 201"
                  else
                    puts "Error reserving car: #{response.body}"
                  end
                else
                  puts "Invalid parameters, sending 422 Unprocessable Entity error"
                  response = Net::HTTPUnprocessableEntity.new(1.0, 'Unprocessable Entity')
                end

                puts response.code
            

          </code>
        </pre>
      </div>
    </div>
  </div>
  </div>
</div>

  </section>
  </div>s
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coders Hub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": ":reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

  </head>
  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>